PROGRAM =       if_else_2
OBJS    =       if_else_2.o
SRCS    =       $(OBJS:%.o=%.c)
CC      =       gcc
CFLAGS  =       -g -Wall
LDFLAGS =

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)
