@startuml jissyu4_3
skinparam{
    BackgroundColor #bbb
    DefaultFontColor #000
    SequenceLifeLineBorderColor #fff
    SequenceLifeLineBorderColor #fff
    BoundaryBorderColor #00f
    BoundaryBackgroundColor #aff
    ControlBorderColor #f00
    ControlBackgroundColor #faa
    ActorBackgroundColor #ffa
    ActorBorderColor #ff0
    ArrowColor #000
}

actor ユーザー as user
boundary ブラウザ as browser
control web.php as web
control Jissyu4_3Controller as controller
boundary input.blade.php as input
control Jissyu4_3Request as Request
control Jissyu4_3Myrule as Myrule
boundary output.blade.php as output

user -> browser:該当ページをリクエスト[/jissyu8]
browser -> web:GET[/jissyu8]
web -> controller:@index
controller -> input

user -> input:送信ボタンをクリック
web <- input:POST
web -> Request:フォームリクエスト
Request -> Myrule:マイルール呼び出し
Request <-- Myrule
web <-- Request

web -> controller:@post
alt #DarkGreen 成功
    controller -> output
else #DarkRed エラー発生
    controller -> input
end
@enduml