@startuml kouka2_1
actor "ユーザー" as user
boundary "ブラウザ" as browser
control "web.php" as web
control "Kouka2_1Controller" as controller
boundary "Restdata"
boundary "index.blade.php" as index
boundary "show.blade.php" as show

user -> browser :該当ページをリクエスト[/kouka2_1]
browser -> web :GET[/kouka2_1]
web -> controller :@index
controller -> Restdata :all()
controller <-- Restdata
controller -> index

user -> browser :検索ボタンを押下
browser -> web :GET[/kouka2_1/find]
web -> controller :@find
controller -> controller :where()->first()
controller <-- controller
controller -> show
@enduml