PROGRAM =       struct_7
OBJS    =       struct_7.o
SRCS    =       $(OBJS:%.o=%.c)
CC      =       gcc
CFLAGS  =       -g -Wall
LDFLAGS =

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)