PROGRAM =       func_3
OBJS    =       func_3.o
SRCS    =       $(OBJS:%.o=%.c)
CC      =       gcc
CFLAGS  =       -g
LDFLAGS =

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)
