# Generated by Django 3.0.4 on 2020-09-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kouka2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=1000)),
                ('Area', models.CharField(max_length=1000)),
                ('Delivery', models.CharField(max_length=1000)),
                ('Price', models.IntegerField(default=0)),
                ('Attachment', models.CharField(max_length=1000)),
            ],
        ),
    ]
