# Generated by Django 3.0.4 on 2020-09-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('未回答', '未回答')], max_length=100)),
                ('belong', models.CharField(choices=[('システム開発', 'システム開発'), ('AIデータサイエンス', 'AIデータサイエンス'), ('高度システム開発', '高度システム開発'), ('ネットワークセキュリティ', 'ネットワークセキュリティ')], max_length=100)),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('PHP', 'PHP'), ('C言語', 'C言語'), ('Go言語', 'Go言語'), ('オブジェクト指向設計', 'オブジェクト指向設計'), ('ディープラーニング', 'ディープラーニング'), ('データサイエンス', 'データサイエンス'), ('ネットワークプログラミング', 'ネットワークプログラミング'), ('セキュアプログラミング', 'セキュアプログラミング'), ('クラウドネイティブプログラミング', 'クラウドネイティブプログラミング')], max_length=100)),
            ],
        ),
    ]
