# Generated by Django 3.1.1 on 2020-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default=1, max_length=100)),
                ('belong', models.CharField(default=1, max_length=100)),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
    ]
